### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by ThanasisM** [gfinak/BioC2015OpenCyto#2]
Hi,
I tried to install the package, but failed.
I think the problem lies on the missing .nc file in the extdata folder.

I would appreciate any tips on how to make it work.

Best,
Thanasis

> library(devtools)
> install_github("gfinak/BioC2015OpenCyto")
Downloading GitHub repo gfinak/BioC2015OpenCyto@master
from URL https://api.github.com/repos/gfinak/BioC2015OpenCyto/zipball/master
Installing BioC2015OpenCyto
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/l_/n_211gls1c3961p8t00sc3y00000n5/T/Rtmpkg9Nfc/devtools10065187dea82/gfinak-BioC2015OpenCyto-f8183af'  \
  --library='/Users/tmargaritis/Library/R/3.3/library' --install-tests 

During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing *source* package 'BioC2015OpenCyto' ...
** R
** data
** inst
** preparing package for lazy loading
Warning: package 'ggcyto' was built under R version 3.3.1
Warning: package 'ggplot2' was built under R version 3.3.2
Warning: package 'BH' was built under R version 3.3.2
Warning: package 'flowWorkspace' was built under R version 3.3.1
** help
*** installing help indices
** building package indices
loading R object...
loading tree object...
Error in .load_gs(output = path, files = files) : 
  .nc file missing in /Users/tmargaritis/Library/R/3.3/library/BioC2015OpenCyto/extdata/tbdata
ERROR: installing package indices failed
* removing '/Users/tmargaritis/Library/R/3.3/library/BioC2015OpenCyto'
Error: Command failed (1)

> R.version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.0                         
year           2016                        
month          05                          
day            03                          
svn rev        70573                       
language       R                           
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational

**Comment by gfinak** [comment]
Okay, there's a large data set that needs to be downloaded to the installations' extdata directory. 
Apparently the script to do that isn't working properly.

To get around this, clone the repository and build the package with R CMD build --no-build-vignettes 
Then install the built package. Next go into the source tree /data directory and run the script tbdata.R 
It should download the ncdf file to the package installation directory.
Then, you should be able to load the data in an R session via:
`gating_set_location = list.files(file.path(system.file("extdata",package="BioC2015OpenCyto"),"tbdata"),full=TRUE)`
`tbdata = load_gs(gating_set_location)`

There may be other issues as you work through the vignette as some of the tools API has evolved.

**Comment by ThanasisM** [comment]
Thanks for the info! Building packages is not my expertise yet. I am sure more experienced people will find this response helpful.

Thanks for your great packages and contributions to science
